FROM golang:1.22-alpine AS builder
WORKDIR /
COPY ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/main.go

FROM gcr.io/distroless/static
WORKDIR /
COPY --from=builder /app /app
# COPY --from=builder /app/config.toml .
USER 1000:1000
EXPOSE 8080
CMD ["app/app"]
