name: Trigger Workflow with Value

on:
  push:
    branches:
      - main

jobs:
  trigger-second-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Send value to second workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/<your-username>/<your-repo>/dispatches \
          -d '{"event_type":"custom_event","client_payload":{"value":"some_value"}}'
