# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      # - name: Run go mod tidy
      #   run: go mod tidy
      - name: Log in to Docker Hub
        run: echo "test123!@#" | docker login -u "shiv098" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t shiv098/test01:latest .
      - name: Push Docker image to Docker Hub
        run: |
          docker push shiv098/test01:latest
