name: Save FOO

on: 
  workflow_dispatch:
    inputs:
      foo:
        description: "Set the FOO variable"
        required: true
        default: "example_value"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save FOO as artifact
        run: echo "${{ github.event.inputs.foo }}" > foo.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: foo_artifact
          path: foo.txt
