name: Trigger CircleCI with Cypress Grep Tags

on:
  workflow_dispatch:
    inputs:
      grep_tag:
        description: Choose the Cypress grep tag to run
        required: true
        default: smoke
        type: choice
        options:
          - smoke
          - regression
          - full-suite
          - critical
      branch_name:
        description: Name of the branch to trigger the CircleCI pipeline
        required: true
        default: test2  # Default to main, but you can select any branch
        type: string

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline with Selected Grep Tag
        env:
          CIRCLE_API_TOKEN: ${{ secrets.CIRCLE_API_TOKEN }}
          BRANCH_NAME: ${{ inputs.branch_name }}  # Use the branch name from input
          CYPRESS_GREP_TAGS: ${{ inputs.grep_tag }}
        run: |-
          curl -u ${CIRCLE_API_TOKEN}: \
            --url 'https://circleci.com/api/v2/project/gh/i6systems/in2plane-cloud/pipeline' \
            --header 'Content-Type: application/json' \
            --data "{\"branch\":\"${BRANCH_NAME}\", \"cypress_grep_tags\":\"${CYPRESS_GREP_TAGS}\"}"
