name: Save Grep Tag

on:
  workflow_dispatch:
    inputs:
      grep_tag:
        description: Choose the Cypress grep tag to run
        required: true
        default: smoke
        type: choice
        options:
          - smoke
          - regression
          - full-suite
          - critical

jobs:
  save-grep-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set grep_tag as environment variable
        run: echo "${{ inputs.grep_tag }}" > grep_tag.txt

      - name: Upload grep_tag as artifact
        uses: actions/upload-artifact@v3
        with:
          name: grep_tag_artifact
          path: grep_tag.txt
