# This is a basic workflow to help you get started with Actions

name: CI
env:
    USERNAME : ${{secrets.USERNAME}}
    PASSWORD : ${{secrets.PASSWORD}}
    SECURITY_TOKEN : ${{secrets.SECURITY_TOKEN}}
    
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.18
     
      # - name: Run go mod tidy
      #   run: go mod tidy
      - name: Log in to Docker Hub
        run: echo "test123!@#" | docker login -u "shiv098" --password-stdin
      - name: Set up environment variables
        run: |
          export USERNAME="${{ secrets.USERNAME }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export SECURITY_TOKEN="${{ secrets.SECURITY_TOKEN }}"
      - name: Environment list
        uses: actions/setup-go@v3
        with:
            USERNAME : ${{secrets.USERNAME}}
            PASSWORD : ${{secrets.PASSWORD}}
            SECURITY_TOKEN : ${{secrets.SECURITY_TOKEN}}  
      - name: Build Docker image
        run: |
          docker build --tag shiv098/test03:latest \
            --build-arg USERNAME=${{ secrets.USERNAME }} \
            --build-arg PASSWORD=${{ secrets.PASSWORD }} \
            --build-arg SECURITY_TOKEN=${{ secrets.SECURITY_TOKEN }} \
            .
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
      - name: Push Docker image to Docker Hub
      
        run: |
          docker push shiv098/test03:latest
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
      - name: Run Docker image to Docker Hub
        run: |
          docker run --tag shiv098/test03:latest \
            --build-arg USERNAME=${{ secrets.USERNAME }} \
            --build-arg PASSWORD=${{ secrets.PASSWORD }} \
            --build-arg SECURITY_TOKEN=${{ secrets.SECURITY_TOKEN }} \
            .
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}

     
      # - name: Test
      #   run: go test -v ./login.go
     
