name: Use Value Workflow

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  retrieve-value:
    runs-on: ubuntu-latest
    steps:
      - name: Use received value
        run: |
          echo "Received value: ${{ github.event.client_payload.value }}"
          # You can use this value in subsequent steps or save to config.yml
