name: Check Python Version

# This specifies when the workflow will run. In this case, it runs on every push or pull request to the 'main' branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-python-version:
    runs-on: ubuntu-latest  # The OS where the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository

      - name: Setup Python
        uses: actions/setup-python@v4  # Sets up the required Python version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python Version
        run: python --version  # Command to check and output the Python version

      - name: Check if Python version is compatible
        run: |
          python -c "import sys; assert sys.version_info >= (3, 7), 'Python version is too low!'"
      - name: Use the environment variable
        run: echo "The value of GREP_TAG is $GREP_TAG"
