name: Retrieve FOO

on: push

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: foo_artifact

      - name: Read FOO value
        run: |
          FOO=$(cat foo.txt)
          echo "FOO value is $FOO"
