name: Retrieve Grep Tag

on:
  workflow_dispatch:

jobs:
  retrieve-grep-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Download grep_tag artifact
        uses: actions/download-artifact@v3
        with:
          name: grep_tag_artifact
          path: .

      - name: Read and use the grep_tag value
        run: |
          grep_tag=$(cat grep_tag.txt)
          echo "The value of GREP_TAG is ${grep_tag}"

      - name: Use grep_tag in subsequent steps
        run: echo "Grep tag is being used as: $grep_tag"
